import Head from "next/head";
import BrandList from "../components/Aside/BrandList";
import DailyHits from "../components/Aside/DailyHits";
import Main from "../components/Wrapper/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mobile sell.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div className="grid grid-cols-[300px_1fr] gap-2">
          <aside className="flex flex-col gap-4">
            <BrandList />
            <DailyHits />
          </aside>
          <div>Hello</div>
        </div>
      </Main>
    </div>
  );
}
