import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import BrandList from "../components/Aside/BrandList";
import DailyHits from "../components/Aside/DailyHits";
import Features from "../components/Section/Features";
import News from "../components/Section/News";
import Main from "../components/Wrapper/Main";
import { setCategory } from "../redux/Slice/categorySlice";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mobile sell.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div className="main-section">
          <aside className="flex flex-col gap-2  ">
            <BrandList />
          </aside>
          <section className="flex flex-col xl:fixed-column  overflow-x-scroll scrollbar-hide gap-2">
            <Features heading="Top Mobiles" num={[0, 5]} />
            <Features heading="New Mobiles" num={[6, 11]} />
            <News />
          </section>
          <aside>
            <DailyHits />
          </aside>
        </div>
      </Main>
    </div>
  );
}
